### ISSUE TITLE
Problem species in Canadian species list

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/MetawebTransferLearning#10]
I was having a quick look at the 'suppmat.pdf` and I see (at least) _Berardius bairdii_ (beaked whale) is present... Did we decide to keep marine mammals and I blocked that from hey memory or do we need to update the species filter?

**Comment by TanyaS08** [comment]
Side note looks like _Berardius bairdii_ can take on chipmunks though (edit) low probability though

**Comment by tpoisot** [comment]
Good catch. Let's maybe clean the species list some more?

**Comment by tpoisot** [comment]
They're from IUCN, btw, but yeah the whale doesn't really make sense

**Comment by TanyaS08** [comment]
Also caught _Neovison macrodon_ so some extinct species are also creeping in, which is weird... Might be worth re-downloading/checking the IUCN list since you child be able to filter out marine (at least) at the source...

**Comment by TanyaS08** [comment]
Those ticked off have been 'coded' to be removed
- [x]  Sea mink (_Neovison macrodon_) - Extinct
- [x]  Sea otter (_Enhydra lutris_) - I think we decided to call it marine
- [ ]  Alaska marmot (_Marmota broweri_) - considered as uncertain distribution in CAN by ICUN
- [x]  KOGIIDAE - moar whales...
- [x]  PHOCOENIDAE - porpoises

**Comment by TanyaS08** [comment]
[cross post] _Mus musculus_ is double in the `IUCN_gbif_names.csv` not sure if thats a problem later in the pipeline since at least one would drop out when decomposing
